/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2026 Catium2006
 */

// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ws2812 //
// ------ //

#define ws2812_wrap_target 0
#define ws2812_wrap 7
#define ws2812_pio_version 0

static const uint16_t ws2812_program_instructions[] = {
            //     .wrap_target
    0x6021, //  0: out    x, 1
    0x0025, //  1: jmp    !x, 5
    0xf001, //  2: set    pins, 1                [16]
    0xee00, //  3: set    pins, 0                [14]
    0x0000, //  4: jmp    0
    0xe801, //  5: set    pins, 1                [8]
    0xf600, //  6: set    pins, 0                [22]
    0x0000, //  7: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2812_program = {
    .instructions = ws2812_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = ws2812_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ws2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2812_wrap_target, offset + ws2812_wrap);
    return c;
}
#endif

